# Generated by Django 5.1.5 on 2025-01-22 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TODOO',
        ),
    ]
